import { Task } from '@/app/types/task';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Implement user authentication',
    description: 'Set up JWT-based authentication with refresh tokens and secure session management.',
    status: 'in-progress',
    priority: 'high',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['backend', 'security'],
  },
  {
    id: '2',
    title: 'Design landing page mockups',
    description: 'Create high-fidelity mockups for the new marketing landing page with responsive layouts.',
    status: 'completed',
    priority: 'medium',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['design', 'frontend'],
  },
  {
    id: '3',
    title: 'Database schema optimization',
    description: 'Review and optimize database indexes for improved query performance on user data tables.',
    status: 'todo',
    priority: 'high',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['database', 'performance'],
  },
  {
    id: '4',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints with request/response examples and authentication requirements.',
    status: 'in-progress',
    priority: 'medium',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now()).toISOString(),
    tags: ['documentation', 'backend'],
  },
  {
    id: '5',
    title: 'Set up CI/CD pipeline',
    description: 'Configure automated testing and deployment pipeline using GitHub Actions.',
    status: 'todo',
    priority: 'low',
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['devops', 'automation'],
  },
  {
    id: '6',
    title: 'Implement real-time notifications',
    description: 'Add WebSocket support for real-time push notifications to users.',
    status: 'todo',
    priority: 'medium',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['backend', 'feature'],
  },
  {
    id: '7',
    title: 'Code review: Payment integration',
    description: 'Review and test the new payment gateway integration before production deployment.',
    status: 'in-progress',
    priority: 'high',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now()).toISOString(),
    updatedAt: new Date(Date.now()).toISOString(),
    tags: ['review', 'payment'],
  },
  {
    id: '8',
    title: 'Update dependencies',
    description: 'Update all npm packages to latest stable versions and test for breaking changes.',
    status: 'completed',
    priority: 'low',
    dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['maintenance'],
  },
];
